<?php

function islandora_entities_entity_info() {
  $entity['fedora_object'] = array(
    'label' => t('Fedora Object'),
    'module' => 'islandora_entities',
    'description' => t('Fedora Object'),
    'entity keys' => array(
      'id' => 'id',
      'label' => 'label',
    ),
    'entity class' => 'FedoraObjectEntity',
    'controller class' => 'FedoraObjectEntityController',
    'bundles' => array(
      'fedora_object' => array(
        'label' => t('Fedora object'),
      ),
    ),
  );

  return $entity;
}

function islandora_entities_entity_property_info() {
  $info['fedora_object']['properties'] = array(
    'id' => array(
      'label' => t('PID'),
      'type' => 'text',
    ),
    'label' => array(
      'label' => t('Label'),
      'type' => 'text',
    ),
    'creator' => array(
      'label' => t('Creator'),
      'type' => 'text',
    ),
  );

  return $info;
}